version: "3.3"

services:
  go:
    build: .
    volumes:
      - ./src:/go/src
    command: go run ./src/main.go &
    ports:
      - 8083:8083
networks:
  default:
    external:
      name: pentago-symfony_default
